/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Backend.ParseJson;
import Backend.User;
import java.util.ArrayList;
import getout.GETOUT;
import java.util.function.Predicate;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author S332896109
 */
public class DeleteUser extends javax.swing.JFrame {

    /**
     * Creates new form DeleteUser
     */
    Object[][] data;

    public DeleteUser() {
        //System.out.println(GETOUT.users.get(9).getEmail());
        int accNum = LoginScreen.currentUser.getEmail().equals(GETOUT.ADMIN_EMAIL) ? 1 : 2;
        int counter = 0;
        data = new Object[GETOUT.users.size() - accNum][3];
        for (int i = 0; i < GETOUT.users.size() - accNum; i++) {
            for (int j = counter; j < GETOUT.users.size(); j++) {
                counter++;
                if (!GETOUT.users.get(j).getEmail().equals(GETOUT.ADMIN_EMAIL)
                        && !GETOUT.users.get(j).getEmail().equals(LoginScreen.currentUser.getEmail())) {
                    System.out.println(j);

                    data[i][0] = GETOUT.users.get(j).getName();
                    data[i][1] = GETOUT.users.get(j).getEmail();
                    data[i][2] = false;
                    break;
                }

            }

        }
        initComponents();
        table.setOpaque(false);
        ((DefaultTableCellRenderer) table.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        table.setShowGrid(false);
        table.getTableHeader().setOpaque(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        confirmDelete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(355, 518));
        setSize(new java.awt.Dimension(365, 518));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Users");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 150, 33);

        confirmDelete.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        confirmDelete.setForeground(new java.awt.Color(255, 255, 255));
        confirmDelete.setText("Confirm Delete");
        confirmDelete.setBorder(null);
        confirmDelete.setBorderPainted(false);
        confirmDelete.setContentAreaFilled(false);
        confirmDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        confirmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(confirmDelete);
        confirmDelete.setBounds(110, 390, 130, 50);

        cancel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.setBorder(null);
        cancel.setBorderPainted(false);
        cancel.setContentAreaFilled(false);
        cancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(140, 450, 39, 17);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jScrollPane1.setOpaque(false);

        table.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "Name", "Email", "Delete?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setOpaque(false);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setSelectionForeground(new java.awt.Color(204, 255, 255));
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 320, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DeleteUserBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 350, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        new MenuScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void confirmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteActionPerformed

        for (int i = 0; i < table.getModel().getRowCount(); i++) {
            if ((boolean) table.getValueAt(i, 2)) {
                final String TEMP_EMAIL = (String) table.getValueAt(i, 1);
                GETOUT.users.removeIf((User u) -> u.getEmail().equals(TEMP_EMAIL));
            }
        }
        ParseJson.writeToFile(GETOUT.users, GETOUT.USERS_FILE_PATH);
        new MenuScreen().setVisible(true);
        java.awt.EventQueue.invokeLater(() -> {
            new ErrorPanel("User Deleted Successfully", true).setVisible(true);
        });
        dispose();
    }//GEN-LAST:event_confirmDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirmDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
