/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Backend.Login_DEPRECIATED;
import Backend.SendEmail;
import Backend.User;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author S331471193
 */
public class EmailScreen extends javax.swing.JFrame {

    /**
     * Creates new form EmailScreen
     *
     * @param users
     */
    Object[][] data;

    public EmailScreen(ArrayList<User> users) {
        data = new Object[users.size()][3];
        for (int i = 0; i < users.size(); i++) {

            data[i][0] = users.get(i).getName();
            data[i][1] = users.get(i).getEmail();
            data[i][2] = false;
        }
        initComponents();
        table.setOpaque(false);
        ((DefaultTableCellRenderer) table.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        table.setShowGrid(false);
        table.getTableHeader().setOpaque(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        body = new javax.swing.JTextArea();
        checkAll = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        send = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 432));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 432));
        getContentPane().setLayout(null);

        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "Name", "Email", "Check to email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setOpaque(false);
        table.setRowHeight(24);
        table.setSelectionBackground(new java.awt.Color(153, 204, 255));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 310, 246);

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Subject:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 60, 50, 17);

        subject.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        subject.setForeground(new java.awt.Color(255, 255, 255));
        subject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        subject.setCaretColor(new java.awt.Color(255, 255, 255));
        subject.setOpaque(false);
        getContentPane().add(subject);
        subject.setBounds(390, 60, 149, 19);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Body:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(338, 100, 40, 17);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        body.setColumns(20);
        body.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        body.setForeground(new java.awt.Color(255, 255, 255));
        body.setLineWrap(true);
        body.setRows(5);
        body.setWrapStyleWord(true);
        body.setAutoscrolls(false);
        body.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        body.setCaretColor(new java.awt.Color(255, 255, 255));
        body.setOpaque(false);
        body.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        body.setSelectionColor(new java.awt.Color(51, 204, 255));
        jScrollPane1.setViewportView(body);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 100, 245, 210);

        checkAll.setForeground(new java.awt.Color(255, 255, 255));
        checkAll.setText("Select All");
        checkAll.setContentAreaFilled(false);
        checkAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAllActionPerformed(evt);
            }
        });
        getContentPane().add(checkAll);
        checkAll.setBounds(209, 320, 100, 23);

        jButton2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Discard Email");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 360, 90, 17);

        send.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setText("Send");
        send.setBorder(null);
        send.setBorderPainted(false);
        send.setContentAreaFilled(false);
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send);
        send.setBounds(540, 320, 90, 30);

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Compose Message");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 10, 230, 33);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubmitButton.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 320, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmailScreen.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 650, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuScreen().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
//row, column
    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        ArrayList<String> tempTo = new ArrayList<>();
        for(int i = 0; i<table.getModel().getRowCount(); i++){
            if ((boolean)table.getValueAt(i, 2)){
                tempTo.add((String)table.getValueAt(i, 1));
            }
        }
        if(!tempTo.isEmpty()){
        String [] to = tempTo.toArray(new String[tempTo.size()]);
                
        try {
            LoginScreen.email.sendEmail(to, LoginScreen.currentUser.getEmail(), subject.getText(), body.getText());
            new ErrorPanel("Sent Successfully", true).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(EmailScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(EmailScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            new ErrorPanel("You must have at least one recipient selected!").setVisible(true);
        }
// String[] to = {"emailerTreeMailer@gmail.com"};
        //SendEmail.SendMessage(Login_DEPRECIATED.getInstance(), to, subject.getText(), body.getText());
    }//GEN-LAST:event_sendActionPerformed

    private void checkAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAllActionPerformed
        for (int i = 0; i < data.length; i++) {
            table.setValueAt(true, i, 2);
        }
        checkAll.setSelected(false);
    }//GEN-LAST:event_checkAllActionPerformed

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea body;
    private javax.swing.JCheckBox checkAll;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton send;
    private javax.swing.JTextField subject;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
